# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baisiMyTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baisiMyTest
	pod 'SDWebImage', '~> 5.0'
  target 'baisiMyTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'baisiMyTestUITests' do
    # Pods for testing
  end

end
